services:
  - type: web
    name: royalschoolmgtsystem
    env: php
    plan: free
    buildCommand: "echo 'No build step required'"
    startCommand: "php -S 0.0.0.0:$PORT -t ."
    autoDeploy: true
